# Generated by Django 4.1.1 on 2022-10-05 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_completed',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_started',
            field=models.DateField(default=datetime.date(2022, 10, 5)),
        ),
    ]
