# Generated by Django 4.1.2 on 2022-10-12 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_date_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_started',
            field=models.DateField(default=datetime.date(2022, 10, 12)),
        ),
    ]
