# Generated by Django 4.1.2 on 2022-10-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('redditor', models.CharField(blank=True, max_length=50, null=True)),
                ('img_path', models.ImageField(upload_to='images/cats')),
            ],
        ),
    ]
